Hw 03 mongo db
gradussus/goit-node-hw-02-06 pull request #2
Opened 2023-02-12 17:50 UTC by gradussus

Проханя перевірити. Після ДЗ №2 змінив структуру проєкту надихнувшись відеолекціями)

2023-02-13 16:35 UTC, Eastvarga requested changes
Є зауваження.
Раути повинні повертати контакти або масив контактів

2023-02-13 16:35 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ status: "success" });
Що за завданням повинно повертати створення контакту?

2023-02-13 16:35 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ message: `Contact with ID ${contactId} is updated` });
Повертайте Оновлений контакт.

2023-02-13 16:35 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ message: `Contact with ID ${contactId} is updated` });
За результатом роботи функції повертає оновлений об'єкт контакту і статусом 200.  Де виконується ця умова завдання?

2023-02-13 16:35 UTC, Eastvarga commented on schemas/validation.js
>  });
Додайте умову для того щоб хочаб одне поле було присутнє у тілі запиту - це є у Джой

2023-02-13 16:35 UTC, Eastvarga commented on services/contactsService.js
> +    $set: { name, phone, email },
Вам потрібно повертати оновлений об'єкт, чи так це зараз - перевірте.

2023-02-13 16:35 UTC, Eastvarga commented on services/contactsService.js
> +  const isUpdated = await Contact.findByIdAndUpdate(id, { $set: { favorite } });
теж саме. Не впевнений що Ви отримаєте оновлений контакт (старий скоріш за все)

2023-02-15 15:54 UTC, gradussus commented
Виправив зауваження

2023-02-15 20:50 UTC, Eastvarga requested changes
Є зауваження

2023-02-15 20:50 UTC, Eastvarga commented on models/contacts.js
> +  res.status(201).json({ status: "success" });
Не може бути 201 статус видалення об'екту
тай в загалі у вас тут гармидер якийсь - не вірна логіка всередині removeContact

2023-02-15 20:50 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ contacts });
res.json(contacts ); так буде краще - додаткова вкладеність зайва

2023-02-15 20:50 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ contact });
теж саме  res.json(contact); краще

2023-02-15 20:50 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ message: `Contact with ID ${contactId} deleted succuessfully` });
Ви вже вище відповідь дали - хіба у Вас при тестуванні помилки не виникали?

2023-02-15 20:50 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ contact });
невірний статус створення контакту та зайва вкладеність
  resstatus(201).json(contact); краще

2023-02-15 20:50 UTC, Eastvarga commented on models/contacts.js
> +  res.json({ contact });
зайва вкладеність знову

2023-02-15 20:50 UTC, Eastvarga commented on services/contactsService.js
> +    $set: { name, phone, email },
я так і не бачу щоб Ви зрозуміли свою помилку - де {new: true} додаткова опція у методі findByIdAndUpdate?

2023-02-15 20:50 UTC, Eastvarga commented on services/contactsService.js
> +  const contact = await Contact.findById(id);
зовсім зайве - чи перевіряли ви що поверне findByIdAndUpdate, та що може повернути таке findById якщо попередній метод нічого не повернув? Бо findById це те що їх об'єднує.

2023-02-16 08:33 UTC, gradussus commented on models/contacts.js
> +  res.status(201).json({ status: "success" });
Працював на двох компьютерах і через це виникли конфлікти. Тут не догледів коли вирішував їх

2023-02-16 18:07 UTC, Eastvarga approved these changes

2023-02-16 18:07 UTC, merged