Hw 04 auth
gradussus/goit-node-hw-02-06 pull request #3
Opened 2023-02-25 14:51 UTC by gradussus

прохання перевірити

2023-02-26 09:37 UTC, Eastvarga requested changes
Є зауваження.

2023-02-26 09:37 UTC, Eastvarga commented on middlevares/authMiddlevare.js
> +  const { _id } = jwt.decode(token, process.env.JWT_SECRET);
Використовуйте verify для верифікації токена, декодування лише повертає пейлоад без перевірки самого токена.
Також, зовсім зайва перевірка перша - навіщо двічі робити то?
 const { _id } = jwt.decode(token, process.env.JWT_SECRET); достатньо

2023-02-26 09:37 UTC, Eastvarga commented on models/contacts.js
> +  res.json(contact[0]);
Повернення контакту по айді не повинно повертати масив - це значить що Ви невірно користуєтесь методами mongoose

2023-02-26 09:37 UTC, Eastvarga commented on models/contacts.js
> +  const isContactDeleted = await removeContactService(contactId, _id);
видалення не повертає буль - повинна повертати видалений елемент. Дослідіть що повертае метод видалення з БД (mongoose)

2023-02-26 09:37 UTC, Eastvarga commented on services/contactsService.js
> +  if (favorite) {
впевнені що favorite це не буль, та фільтрування контактів по favorite= false поверне вам всі контакти де  favorite= false ?

2023-02-26 09:37 UTC, Eastvarga commented on services/contactsService.js
> +  const contacts = await Contact.find({ owner }).skip(skip).limit(limit);
поганий підхід - Ви повинні формувати аргументи запиту - та робити лише один запит до бази з цими (сформованими) аргументами
Contact.find(options)
самі опції формуєте в залежності від того що прийде у запиті

2023-02-26 09:37 UTC, Eastvarga commented on services/contactsService.js
> +  const contact = await Contact.find({ $and: [{ owner }, { _id: id }] });
є метод саме для одного елементу findOne

2023-02-26 09:37 UTC, Eastvarga commented on services/usersService.js
> +  return loginUser;
не можна повертати креди юзера - пароль, його хеш, токен, тощо

2023-02-26 09:37 UTC, Eastvarga commented on services/usersService.js
> +  });
у Вас у req.user все є, бо попереду стояти повинен мідлвар авторізації котрий записує юзера у запит, беріть його дані звідти

2023-02-26 09:37 UTC, Eastvarga commented on services/usersService.js
> +  console.log(user);
консоль навіщо?

2023-02-27 19:39 UTC, gradussus commented
Виправив помилки

2023-02-27 19:56 UTC, Eastvarga requested changes
Є зауваження

2023-02-27 19:56 UTC, Eastvarga commented on services/contactsService.js
> +  const isFavorite = JSON.parse(favorite);
так і не зрозуміли що повинно відбуватись.
let options = { owner }
if(favorite){
options = { $and: [{ owner }, { favorite: isFavorite }] }
}

const contacts =  await Contact.find(options ,"",
    {
      skip,
      limit,
    })
хочаб так, і не потрібно прописувати запит у БД двічі

2023-02-27 19:56 UTC, Eastvarga commented on middlevares/authMiddlevare.js
> -  }
чому прибрали перевірку токена на невизначеність, та не перевіряєте тип токену tokenType перед jwt.verify? Вас попередні завдання нічому не навчили?

2023-02-27 19:56 UTC, Eastvarga commented on models/contacts.js
> +  console.log(contact);
консоль зайва

2023-02-27 19:56 UTC, Eastvarga commented on models/contacts.js
> +    message: `Contact with ID ${contactId} deleted succuessfully`,
message: `Contact with ID ${contactId} deleted succuessfully`, зайве достатньо повернути контакт по аналогії з пошуком по айді

2023-02-27 21:29 UTC, gradussus commented
Виправив

2023-02-28 17:59 UTC, Eastvarga approved these changes

2023-02-28 17:59 UTC, merged