Hw 06 email
gradussus/goit-node-hw-02-06 pull request #5
Opened 2023-03-09 10:03 UTC by gradussus

Прохання перевірити

2023-03-09 18:47 UTC, Eastvarga requested changes
Є зауваження

2023-03-09 18:47 UTC, Eastvarga commented on helpers/sendEmail.js
> +
Не буде так процювати бо де Ви загубили sgMail.setApiKey(process.env.SENDGRID_API_KEY);?

2023-03-09 18:47 UTC, Eastvarga commented on models/users.js
> +sgMail.setApiKey(process.env.SENDGRID_API_KEY);
Ш навіщо це тут - якщо Ви його ніде не використовуєте у модулі та навіть не експортуєте - йому місце Вище у зауваженні попереднім

2023-03-09 18:47 UTC, Eastvarga commented on services/usersService.js
> +  }
Невірно - достатньо один раз запросити юзера по пошті та перевіривши його статус верифікації робити подальші дії, двічі робити запит у БД не потрібно

2023-03-10 08:41 UTC, gradussus commented
Виправив помилки

2023-03-10 18:35 UTC, Eastvarga approved these changes

2023-03-10 18:35 UTC, merged